from typing import Any, Tuple

class Mlx:
    def mlx_init(self) -> int: ...
    def mlx_new_window(self, mlx_ptr: int, size_x: int, size_y: int, title: str) -> int: ...
    def mlx_new_image(self, mlx_ptr: int, width: int, height: int) -> int: ...
    def mlx_get_data_addr(self, img_ptr: int) -> Tuple[memoryview, int, int, int]: ...
    def mlx_put_image_to_window(self, mlx_ptr: int, win_ptr: int, img_ptr: int, x: int, y: int) -> int: ...
    def mlx_destroy_image(self, mlx_ptr: int, img_ptr: int) -> int: ...
    def mlx_destroy_window(self, mlx_ptr: int, win_ptr: int) -> int: ...
    def mlx_loop(self, mlx_ptr: int) -> int: ...
    def mlx_loop_exit(self, mlx_ptr: int) -> int: ...
    def mlx_hook(self, win_ptr: int, x_event: int, x_mask: int, funct: Any, param: Any) -> int: ...
    def mlx_key_hook(self, win_ptr: int, funct: Any, param: Any) -> int: ...
    def mlx_mouse_hook(self, win_ptr: int, funct: Any, param: Any) -> int: ...
    def mlx_expose_hook(self, win_ptr: int, funct: Any, param: Any) -> int: ...
    def mlx_loop_hook(self, mlx_ptr: int, funct: Any, param: Any) -> int: ...
    def mlx_string_put(self, mlx_ptr: int, win_ptr: int, x: int, y: int, color: int, string: str) -> int: ...
    def mlx_pixel_put(self, mlx_ptr: int, win_ptr: int, x: int, y: int, color: int) -> int: ...
    def mlx_png_file_to_image(self, mlx_ptr: int, filename: str) -> Tuple[int, int, int]: ...
    def mlx_xpm_file_to_image(self, mlx_ptr: int, filename: str) -> Tuple[int, int, int]: ...
    def mlx_clear_window(self, mlx_ptr: int, win_ptr: int) -> int: ...
    def mlx_get_screen_size(self, mlx_ptr: int) -> Tuple[int, int]: ...
    def mlx_mouse_hide(self, mlx_ptr: int, win_ptr: int) -> int: ...
    def mlx_mouse_show(self, mlx_ptr: int, win_ptr: int) -> int: ...
    def mlx_mouse_move(self, mlx_ptr: int, win_ptr: int, x: int, y: int) -> int: ...
    def mlx_mouse_get_pos(self, mlx_ptr: int, win_ptr: int) -> Tuple[int, int]: ...
    def mlx_do_key_autorepeatoff(self, mlx_ptr: int) -> int: ...
    def mlx_do_key_autorepeaton(self, mlx_ptr: int) -> int: ...
    def mlx_do_sync(self, mlx_ptr: int) -> int: ...
    def mlx_sync(self, mlx_ptr: int, cmd: int, arg: Any) -> int: ...
